{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6-final"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "Python 3.7.6 64-bit ('base': conda)",
   "display_name": "Python 3.7.6 64-bit ('base': conda)",
   "metadata": {
    "interpreter": {
     "hash": "3557435acd75fc5faa5951f595f998356aaec2c348ba8ce54025a59aa5752b02"
    }
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "source": [
    "# Personal notes\n",
    "\n",
    "*this is not practicle*: \n",
    "`print(add(5, 10))`\n",
    "\n",
    "---\n",
    "Also, using python test_calc.py is not going to work.\n",
    "\n",
    "To make it work, you need to run:\n",
    "\n",
    "`python -m unittest test_calc.py`\n",
    "\n",
    "---\n",
    "\n",
    "\n",
    "```\n",
    "if __name__ == '__main__':\n",
    "    unittest.main()\n",
    "```\n",
    "\n",
    "makes it run all methods from our unit test without the necessity of using `python -m unittest test_calc.py`\n",
    "\n",
    "--- \n",
    "\n",
    "If you don't use `test_` in the beginning of the name of your functions, it will not be counted as a test method\n",
    "\n",
    "--- \n",
    "\n",
    "You can use additional tests inside of the same testing method to make sure it accepts different cases\n",
    "```\n",
    "def test_add(self):\n",
    "    self.assertEqual(calc.add(10,5), 15)\n",
    "    self.assertEqual(calc.add(-1,1), 0)\n",
    "    self.assertEqual(calc.add(-1,-1), -2)\n",
    "\n",
    "```\n",
    "\n",
    "--- \n",
    "\n",
    "It is a good practice to add new tests for every bug or problem that you had, so you can assure it will not happen again\n",
    "\n",
    "---\n",
    "\n",
    "`self.assertRaises(ValueError, calc.divide, 10, 0)`\n",
    "\n",
    "The method is passed as a parameter because if you use as `calc.divide(10,0)` it will rise an error and the unit test will fail\n",
    "\n",
    "---\n",
    "\n",
    "You can also use the context manager and call it the normal way\n",
    "\n",
    "```\n",
    "# Calling the funcion normally\n",
    "with self.assertRaises(ValueError):\n",
    "    calc.divide(10,0)\n",
    "```\n",
    "\n",
    "---\n",
    "\n",
    "*Set ups and tear downs:*\n",
    "\n",
    "```\n",
    "def setUp(self):\n",
    "    pass\n",
    "\n",
    "def tearDown(self):\n",
    "    pass\n",
    "\n",
    "\n",
    "@classmethod\n",
    "def setUpClass(cls):\n",
    "    print('Set Up Class')\n",
    "\n",
    "@classmethod\n",
    "def tearDownClass(cls):\n",
    "    print('Tear Down Class')\n",
    "\n",
    "```\n",
    "\n",
    "- `setUp` executes **every time** before a test starts.\n",
    "- `tearDown` executes **every time** a test ends.\n",
    "- `setUpClass` **runs once** before all tests.\n",
    "- `tearDownClas` **runs once** after all tests. \n",
    "\n",
    "---\n",
    "\n",
    "**Mocking** \n",
    "\n",
    "with patch('employee.**resquests.get**') as mocked_get:\n",
    "\n",
    "Says that we want to mock that part of the employee module\n",
    "\n",
    "---\n",
    "\n",
    "## Best Practices: \n",
    "\n",
    "Test should be isolated: It shouldn't relly on other tests, it should be able to run by itself.\n"
   ],
   "cell_type": "markdown",
   "metadata": {}
  }
 ]
}